d = f.Get("LCT Stats")
c = ROOT.TCanvas("myCanvasName","The Canvas Title", 3200,600)
c.Divide(4,1)

pada = c.cd(1)
p1a = d.Get('AllLctQual')
p2a = d.Get('Low pT/AllLctQualLowPt')
p3a = d.Get('High pT/AllLctQualHighPt')
stacka = make_stack([p1a,p2a,p3a])
stacka.Draw("PFC nostack")
stacka.GetXaxis().SetTitle("Quality")
stacka.GetYaxis().SetTitle("LCTs")
stacka.SetTitle("All LCT Quality")
draw_canv(pada, logy=useLogY, legend_coords=(0.11, 0.6, 0.4, 0.89))

padb = c.cd(2)
d = f.Get("LCT Stats")
p1b = d.Get('PhiPairLctQual')
p2b = d.Get('Low pT/PhiPairLctQualLowPt')
p3b = d.Get('High pT/PhiPairLctQualHighPt')
stackb = make_stack([p1b,p2b,p3b])
stackb.Draw("PFC nostack")
stackb.GetXaxis().SetTitle("Quality")
stackb.GetYaxis().SetTitle("LCTs")
stackb.SetTitle("Phi Pair LCT Quality")
draw_canv(padb, logy=useLogY, legend_coords=(0.11, 0.6, 0.4, 0.89))

padc = c.cd(3)
d = f.Get("LCT Stats")
p1c = d.Get('ThetaPairLctQual')
p2c = d.Get('Low pT/ThetaPairLctQualLowPt')
p3c = d.Get('High pT/ThetaPairLctQualHighPt')
stackc = make_stack([p1c,p2c,p3c])
stackc.Draw("PFC nostack")
stackc.GetXaxis().SetTitle("Quality")
stackc.GetYaxis().SetTitle("LCTs")
stackc.SetTitle("Theta Pair LCT Quality")
draw_canv(padc, logy=useLogY, legend_coords=(0.11, 0.6, 0.4, 0.89))

padd = c.cd(4)
d = f.Get("LCT Stats")
p1d = d.Get('QuadLctQual')
p2d = d.Get('Low pT/QuadLctQualLowPt')
p3d = d.Get('High pT/QuadLctQualHighPt')
stackd = make_stack([p1d,p2d,p3d])
stackd.Draw("PFC nostack")
stackd.GetXaxis().SetTitle("Quality")
stackd.GetYaxis().SetTitle("LCTs")
stackd.SetTitle("Quad LCT Quality")
draw_canv(padd, logy=useLogY, legend_coords=(0.11, 0.6, 0.4, 0.89))

c.Draw()


d = f.Get("LCT Stats")
c = ROOT.TCanvas("myCanvasName","The Canvas Title", 3200,600)
c.Divide(4,1)

pada = c.cd(1)
p1a = d.Get('AllLctTheta')
p2a = d.Get('Low pT/AllLctThetaLowPt')
p3a = d.Get('High pT/AllLctThetaHighPt')
stacka = make_stack([p1a,p2a,p3a])
stacka.Draw("PFC nostack")
stacka.GetXaxis().SetTitle("Theta_int")
stacka.GetYaxis().SetTitle("LCTs")
stacka.SetTitle("All LCT Theta")
draw_canv(pada, logy=useLogY)

padb = c.cd(2)
d = f.Get("LCT Stats")
p1b = d.Get('PhiPairLctTheta')
p2b = d.Get('Low pT/PhiPairLctThetaLowPt')
p3b = d.Get('High pT/PhiPairLctThetaHighPt')
stackb = make_stack([p1b,p2b,p3b])
stackb.Draw("PFC nostack")
stackb.GetXaxis().SetTitle("Theta_int")
stackb.GetYaxis().SetTitle("LCTs")
stackb.SetTitle("Phi Pair LCT Theta")
draw_canv(padb, logy=useLogY)

padc = c.cd(3)
d = f.Get("LCT Stats")
p1c = d.Get('ThetaPairLctTheta')
p2c = d.Get('Low pT/ThetaPairLctThetaLowPt')
p3c = d.Get('High pT/ThetaPairLctThetaHighPt')
stackc = make_stack([p1c,p2c,p3c])
stackc.Draw("PFC nostack")
stackc.GetXaxis().SetTitle("Theta_int")
stackc.GetYaxis().SetTitle("LCTs")
stackc.SetTitle("Theta Pair LCT Theta")
draw_canv(padc, logy=useLogY)

padd = c.cd(4)
d = f.Get("LCT Stats")
p1d = d.Get('QuadLctTheta')
p2d = d.Get('Low pT/QuadLctThetaLowPt')
p3d = d.Get('High pT/QuadLctThetaHighPt')
stackd = make_stack([p1d,p2d,p3d])
stackd.Draw("PFC nostack")
stackd.GetXaxis().SetTitle("Theta_int")
stackd.GetYaxis().SetTitle("LCTs")
stackd.SetTitle("Quad LCT Theta")
draw_canv(padd, logy=useLogY)

c.Draw()
